import os
import time
import sys
import code

def typewriter(text, speed=0.05):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(speed)
    print()

def one():
    os.system('cls')
    print("Python is a high-level, versatile programming language created by Dutch software engineer Guido van")
    time.sleep(.1)
    print("Rossum, who began its development in the late 1980s and released the first public version in 1991. Designed")
    time.sleep(.1)
    print("with an emphasis on readability and simplicity, Python uses clean, English-like syntax that makes it easier for")
    time.sleep(.1)
    print("beginners to learn while still offering powerful capabilities for experts. Van Rossum, often referred to as")
    time.sleep(.1)
    print("Python\'s \"Benevolent Dictator for Life\" (BDFL) until he stepped down from that role in 2018, drew inspiration")
    time.sleep(.1)
    print("from languages like ABC and aimed to create a language that encouraged clear, logical code. Over the years,")
    time.sleep(.1)
    print("Python has grown into one of the world\'s most popular languages, used across web development, data")
    time.sleep(.1)
    print("science, automation, artificial intelligence, and scientific computing, supported by a massive global")
    time.sleep(.1)
    print("community and an extensive ecosystem of libraries.")
    time.sleep(.1)
    print("=================================================================================================================\n")
    input("press enter to continue: ")
    os.system('cls')

def two():
    os.system('cls')
    print("Python is good for beginners because it is easy to read and understand. Its code looks simple, almost like")
    time.sleep(.1)
    print("normal English, so new learners don\'t get confused. It also has fewer rules and symbols, making it easier to")
    time.sleep(.1)
    print("write and fix mistakes. Python has a big community, which means there are many tutorials and examples")
    time.sleep(.1)
    print("available online for students. It can also be used for many things like making websites, automating tasks, or")
    time.sleep(.1)
    print("working with data, so beginners can explore different projects without changing languages. Overall, Python")
    time.sleep(.1)
    print("is simple, flexible, and beginner-friendly, which makes it a great first programming language.")
    time.sleep(.1)
    print("=================================================================================================================\n")
    time.sleep(.1)
    input("press enter to continue: ")
    os.system('cls')

def three():
    os.system('cls')
    print("This is a python compiler that helps you to learn how to program using python as a programming language by")
    time.sleep(.1)
    print("choosing an option after you run the program.")
    time.sleep(1)
    print("\nThis compiler also have a quiz to determine if you really learn something in this python learning journey.")
    time.sleep(3)
    print("\nGOODLUCK!!")
    time.sleep(.1)
    input("press enter to continue: ")
    os.system('cls')

def prints():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tprint() is a built-in function in Python that is used to display information on the screen.")
    typewriter("\tAnything you put inside print() will be shown to the user when the program runs.")
    time.sleep(1)
    while True:
        name = input("\nChoose from the selection below :D\n\tA. Printing Text\n\tB. Printing Numbers\n\tC. Printing Text with Numbers\n\tX. Exit\nType here ---> ")
        if name == 'a':
            os.system('cls')
            typewriter("This is how printing text works in python")
            typewriter("INPUT:\n\tprint(\"Hello World\")\n\nOUTPUT:\n\tHello World")
            time.sleep(2)
            input("\npress enter to try how to use print: ")
            os.system('cls')
            typewriter("Type \'exit\' if you want to leave.\n")
            time.sleep(2)
            while True:
                user_code = input(">>> ")
                if user_code.lower() == "exit":
                    typewriter("Exiting compiler...")
                    break               
                try:
                    exec(user_code)
                except Exception as e:
                    print("Error:", e)
            os.system('cls')
        elif name == 'b':
            os.system('cls')
            typewriter("This is how printing numbers works in python")
            typewriter("INPUT:\n\tprint(100)\n\nOUTPUT:\n\t100")
            time.sleep(2)
            input("\npress enter to try how to use print: ")
            os.system('cls')
            typewriter("Type \'exit\' if you want to leave.\n")
            time.sleep(2)
            while True:
                user_code = input(">>> ")
                if user_code.lower() == "exit":
                    typewriter("Exiting compiler...")
                    break               
                try:
                    exec(user_code)
                except Exception as e:
                    print("Error:", e)
            os.system('cls')
        elif name == 'c':
            os.system('cls')
            typewriter("This is how printing text with numbers works in python")
            typewriter("INPUT:\n\tprint(\"My age is\", 18)\n\nOUTPUT:\n\tMy age is 18")
            time.sleep(2)
            input("\npress enter to try how to use print: ")
            os.system('cls')
            typewriter("Type \'exit\' if you want to leave.\n")
            time.sleep(2)
            while True:
                tryss = input(">>> ")
                if tryss.lower() == "exit":
                    typewriter("Exiting compiler...")
                    break               
                try:
                    exec(tryss)
                except Exception as e:
                    print("Error:", e)
            os.system('cls')
        elif name == 'x':
            os.system('cls')
            break
        else:
            print("Invalid Input!")

def variables():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA variable in Python is a name you create to store a value in your program. It works like a container")
    typewriter("\tor a box where you keep information that you want to use later.")
    time.sleep(1)
    typewriter("\tEXAMPLE:\n\t\tname = \'Mark\'\n\t\tage = 18")
    time.sleep(1)
    typewriter("\tyou are storing the words “Mark” and the number 17 inside variables. This makes your program more")
    typewriter("\tflexible because you can save data, change it, and reuse it anytime. Variables are important because")
    typewriter("\tthey help your program remember information, perform calculations, and interact with the user.")
    time.sleep(.5)
    typewriter("\nNow I will show you how to use variable using print")
    input("\npress enter to continue: ")
    typewriter("\nINPUT:\n\tname = \'Mark Andrei\'\n\n\tprint(\"My name is\", name)")
    typewriter("\nOUTPUT:\n\tMy name is Mark Andrei")
    input("\npress enter to try: ")
    os.system('cls')
    typewriter("Type \'exit\' if you want to leave.\n")
    time.sleep(2)
    storage = {}
    while True:
        trys = input(">>> ")
        if trys.lower() == "exit":
            typewriter("Exiting compiler...!")
            break   
        try:
            exec(trys, storage)
        except Exception as e:
            print("Error:", e)
    os.system('cls')

def inputs():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tIn Python, the input() function is a built-in function used to capture user input from the console.")
    typewriter("\tWhen the input() function is called, the program pauses and waits for the user to type something.")
    typewriter("\tThe user\'s input is then returned as a string, regardless of whether the user enters a number, word,")
    typewriter("\tor sentence. You can provide an optional prompt message inside the input() function to guide the user")
    typewriter("\ton what to enter.")
    time.sleep(1)
    typewriter("\n\tEXAMPLE:\n\t\tinput(\"Enter your name here: \")\n\t\tinput(\"Enter your age here: \")")
    time.sleep(1)
    typewriter("\n\tand then it will display \"Enter your name here: \" in the console, and then wait for the user to")
    typewriter("\ttype their name. Once the user presses Enter, the input is returned as a string and can be stored")
    typewriter("\tin a variable for further use.")
    time.sleep(.5)
    typewriter("\nNow I will show you how input works in python")
    input("\npress enter to continue: ")
    typewriter("\nINPUT:\n\tinput(\"Enter your name here: \")")
    typewriter("\nOUTPUT:\n\tEnter your name here:")
    input("\npress enter if you are done reading: ")
    os.system('cls')   
    
def operators():
    os.system('cls')
    while True:
        name = input("\nChoose from the selection below :D\n\tA. Arithmetic Operators\n\tB. Comparison Operators\n\tC. Logical Operators\n\tD. Assignment Operators\n\tX. Exit\nType here ---> ").lower()
        if name == 'a':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tArithmetic operators are the tools Python uses to perform basic math. They work just like the operations")
            typewriter("\twe do in everyday calculations. The + operator adds numbers together, while - subtracts one number from")
            typewriter("\tanother. The * operator multiplies, and / divides numbers, always giving a decimal result. Python also")
            typewriter("\tincludes //, called floor division, which divides but removes anything after the decimal, leaving a whole")
            typewriter("\tnumber. The \'%\' operator gives the remainder after dividing two numbers—useful for checking if a number is")
            typewriter("\teven or odd. Finally, the ** operator raises a number to a power, like squaring or cubing. Together, these")
            typewriter("\toperators allow Python to perform almost any type of math you need.")
            time.sleep(1)
            typewriter("\n\tEXAMPLE:")
            print("\t\t|  Operator:\t|  Meaning:\t\t|  Example:\t|  Result:  |")
            time.sleep(.1)
            print("\t\t|     +\t\t|  Addition\t\t|  3 + 2\t|    5\t    |")
            time.sleep(.1)
            print("\t\t|     -\t\t|  Subtraction\t\t|  5 - 3\t|    2\t    |")
            time.sleep(.1)
            print("\t\t|     *\t\t|  Multiplication\t|  4 * 2\t|    8\t    |")
            time.sleep(.1)
            print("\t\t|     /\t\t|  Division\t\t|  5 / 2\t|   2.5\t    |")
            time.sleep(.1)
            print("\t\t|     //\t|  Floor division\t|  5 // 2\t|    2\t    |")
            time.sleep(.1)
            print("\t\t|     %\t\t|  Modulus (remainder)\t|  5 % 2\t|    1\t    |")
            time.sleep(.1)
            print("\t\t|     **\t|  Exponent\t\t|  2 ** 3\t|    8\t    |")
            time.sleep(.5)
            input("\npress enter if you are done reading: ")
            os.system('cls')
        elif name == 'b':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tComparison operators help Python compare two values and decide whether something is true or false. They")
            typewriter("\tdon\'t give numerical answers—they return either True or False. The == operator checks if two values are")
            typewriter("\tequal, while != checks if they are different. The > and < operators check if one value is greater or")
            typewriter("\tsmaller than another. Their partners, >= and <=, include equality as well, meaning they check for \"greater")
            typewriter("\tor equal\" or \"less or equal.\" These operators are essential when writing conditions, such as deciding if")
            typewriter("\ta user passed a test score or if a number fits within a certain range.")
            time.sleep(1)
            typewriter("\n\tEXAMPLE:")
            print("\t|  Operator:\t|  Meaning:\t\t|  Example:\t|  Result:  |")
            time.sleep(.1)
            print("\t|     ==\t|  Equals\t\t|  5 == 5\t|   true    |")
            time.sleep(.1)
            print("\t|     !=\t|  Not equal\t\t|  5 != 3\t|   true    |")
            time.sleep(.1)
            print("\t|     >\t\t|  Greater than\t\t|  5 > 3\t|   true    |")
            time.sleep(.1)
            print("\t|     <\t\t|  Less than\t\t|  3 < 5\t|   true    |")
            time.sleep(.1)
            print("\t|     >=\t|  Greater or equal\t|  5 >= 5\t|   true    |")
            time.sleep(.1)
            print("\t|     <=\t|  Less or equal\t|  3 <= 5\t|   true    |")
            time.sleep(.5)
            input("\npress enter if you are done reading: ")
            os.system('cls')
        elif name == 'c':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tLogical operators combine multiple conditions to make more complex decisions in Python. The and operator")
            typewriter("\tchecks if both conditions are true before the whole expression becomes true. The or operator is more")
            typewriter("\tflexible it becomes true if at least one condition is true. The not operator acts as a reverser: it flips")
            typewriter("\ta true value to false, and false to true. Logical operators are especially useful when you want Python")
            typewriter("\tto make decisions based on several factors at once, like checking if someone is both over 18 and has an")
            typewriter("\tID, or if a number is either too high or too low.")
            time.sleep(1)
            typewriter("\n\tEXAMPLE:")
            print("\t|  Operator:\t|  Meaning:\t\t\t\t|  Example:\t\t|  Result:  |")
            time.sleep(.1)
            print("\t|     and\t|  True if both are true\t\t|  True and False\t|   false   |")
            time.sleep(.1)
            print("\t|     or\t|  True if at least one is true\t\t|  True or False\t|   true    |")
            time.sleep(.1)
            print("\t|     not\t|  Reverse boolean value\t\t|  not True\t\t|   false   |")
            time.sleep(.5)
            input("\npress enter if you are done reading: ")
            os.system('cls')
        elif name == 'd':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tAssignment operators are used to store values inside variables. The most basic one is =, which simply")
            typewriter("\tassigns a value, like x = 10. Python also provides shortcuts for updating existing values. For example,")
            typewriter("\t+= means \"add something to the existing value,\" so x += 5 is the same as x = x + 5. The same pattern")
            typewriter("\tworks for subtraction (-=), multiplication (*=), division (/=), and the other arithmetic types. These")
            typewriter("\tshortcuts make your code cleaner and faster to write, especially when updating variables repeatedly,")
            typewriter("\tsuch as increasing a score or counting loops.")
            time.sleep(1)
            typewriter("\n\tEXAMPLE:")
            print("\t|  Operator:\t|  Example:\t|  Equivalent To:  |")
            time.sleep(.1)
            print("\t|     =\t\t|  x = 5\t|   Assign 5\t   |")
            time.sleep(.1)
            print("\t|     +=\t|  x += 3\t|   x = x + 3      |")
            time.sleep(.1)
            print("\t|     -=\t|  x -= 3\t|   x = x - 3      |")
            time.sleep(.1)
            print("\t|     *=\t|  x *= 3\t|   x = x * 3      |")
            time.sleep(.1)
            print("\t|     /=\t|  x /= 3\t|   x = x / 3      |")
            time.sleep(.1)
            print("\t|     //=\t|  x //= 3\t|   x = x // 3     |")
            time.sleep(.1)
            print("\t|     %=\t|  x %= 3\t|   x = x % 3      |")
            time.sleep(.1)
            print("\t|     **=\t|  x **= 3\t|   x = x ** 3     |")
            time.sleep(.5)
            input("\npress enter if you are done reading: ")
            os.system('cls')
        elif name == 'x':
            os.system('cls')
            break
        else:
            print("Invalid Input!")
    os.system('cls')
