import os
import time
import sys
import code

def typewriter(text, speed=0.02):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(speed)
    print()

def user_name():
    typewriter("what is your name? ")
    name = input(">>> ")
    return name

def one():
    os.system('cls')
    print("Python is a high-level, versatile programming language created by Dutch software engineer Guido van")
    time.sleep(.1)
    print("Rossum, who began its development in the late 1980s and released the first public version in 1991. Designed")
    time.sleep(.1)
    print("with an emphasis on readability and simplicity, Python uses clean, English-like syntax that makes it easier for")
    time.sleep(.1)
    print("beginners to learn while still offering powerful capabilities for experts. Van Rossum, often referred to as")
    time.sleep(.1)
    print("Python\'s \"Benevolent Dictator for Life\" (BDFL) until he stepped down from that role in 2018, drew inspiration")
    time.sleep(.1)
    print("from languages like ABC and aimed to create a language that encouraged clear, logical code. Over the years,")
    time.sleep(.1)
    print("Python has grown into one of the world\'s most popular languages, used across web development, data")
    time.sleep(.1)
    print("science, automation, artificial intelligence, and scientific computing, supported by a massive global")
    time.sleep(.1)
    print("community and an extensive ecosystem of libraries.")
    time.sleep(.1)
    input("\npress enter to continue: ")
    os.system('cls')

def two():
    os.system('cls')
    print("Python is good for beginners because it is easy to read and understand. Its code looks simple, almost like")
    time.sleep(.1)
    print("normal English, so new learners don\'t get confused. It also has fewer rules and symbols, making it easier to")
    time.sleep(.1)
    print("write and fix mistakes. Python has a big community, which means there are many tutorials and examples")
    time.sleep(.1)
    print("available online for students. It can also be used for many things like making websites, automating tasks, or")
    time.sleep(.1)
    print("working with data, so beginners can explore different projects without changing languages. Overall, Python")
    time.sleep(.1)
    print("is simple, flexible, and beginner-friendly, which makes it a great first programming language.")
    time.sleep(.1)
    time.sleep(.1)
    input("\npress enter to continue: ")
    os.system('cls')

def three():
    os.system('cls')
    print("This is a python compiler that helps you to learn how to program using python as a programming language by")
    time.sleep(.1)
    print("choosing an option after you run the program.")
    time.sleep(1)
    print("\nThis compiler also have a quiz to determine if you really learn something in this python learning journey.")
    time.sleep(3)
    print("\nGOODLUCK!!")
    time.sleep(.1)
    input("\npress enter to continue: ")
    os.system('cls')

def prints():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tprint() is a built-in function in Python that is used to display information on the screen.")
    typewriter("\tAnything you put inside print() will be shown to the user when the program runs.")
    time.sleep(1)
    while True:
        name = input("\nChoose from the selection below :D\n\tA. Printing Text\n\tB. Printing Numbers\n\tC. Printing Text with Numbers\n\tX. Exit\nType here ---> ").lower()
        if name == 'a':
            os.system('cls')
            typewriter("This is how printing text works in python")
            typewriter("INPUT:\n\tprint(\"Hello World\")\n\nOUTPUT:\n\tHello World")
            time.sleep(2)
            input("\npress enter to try how to use print: ")
            os.system('cls')
            typewriter("Type \'exit\' if you want to leave.\n")
            time.sleep(2)
            while True:
                user_code = input(">>> ")
                if user_code.lower() == "exit":
                    typewriter("Exiting compiler...")
                    break               
                try:
                    exec(user_code)
                except Exception as e:
                    print("Error:", e)
            os.system('cls')
        elif name == 'b':
            os.system('cls')
            typewriter("This is how printing numbers works in python")
            typewriter("INPUT:\n\tprint(100)\n\nOUTPUT:\n\t100")
            time.sleep(2)
            input("\npress enter to try how to use print: ")
            os.system('cls')
            typewriter("Type \'exit\' if you want to leave.\n")
            time.sleep(2)
            while True:
                user_code = input(">>> ")
                if user_code.lower() == "exit":
                    typewriter("Exiting compiler...")
                    break               
                try:
                    exec(user_code)
                except Exception as e:
                    print("Error:", e)
            os.system('cls')
        elif name == 'c':
            os.system('cls')
            typewriter("This is how printing text with numbers works in python")
            typewriter("INPUT:\n\tprint(\"My age is\", 18)\n\nOUTPUT:\n\tMy age is 18")
            time.sleep(2)
            input("\npress enter to try how to use print: ")
            os.system('cls')
            typewriter("Type \'exit\' if you want to leave.\n")
            time.sleep(2)
            while True:
                tryss = input(">>> ")
                if tryss.lower() == "exit":
                    typewriter("Exiting compiler...")
                    break               
                try:
                    exec(tryss)
                except Exception as e:
                    print("Error:", e)
            os.system('cls')
        elif name == 'x':
            os.system('cls')
            break
        else:
            print("Invalid Input!")

def variables():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA variable in Python is a name you create to store a value in your program. It works like a container")
    typewriter("\tor a box where you keep information that you want to use later.")
    time.sleep(1)
    typewriter("\tEXAMPLE:\n\t\tname = \'Mark\'\n\t\tage = 18")
    time.sleep(1)
    typewriter("\tyou are storing the words “Mark” and the number 18 inside variables. This makes your program more")
    typewriter("\tflexible because you can save data, change it, and reuse it anytime. Variables are important because")
    typewriter("\tthey help your program remember information, perform calculations, and interact with the user.")
    time.sleep(.5)
    typewriter("\nNow I will show you how to use variable using print")
    input("\npress enter to continue: ")
    typewriter("\nINPUT:\n\tname = \'Mark Andrei\'\n\n\tprint(\"My name is\", name)")
    typewriter("\nOUTPUT:\n\tMy name is Mark Andrei")
    input("\npress enter to try: ")
    os.system('cls')
    typewriter("Type \'exit\' if you want to leave.\n")
    time.sleep(2)
    storage = {}
    while True:
        trys = input(">>> ")
        if trys.lower() == "exit":
            typewriter("Exiting compiler...!")
            break   
        try:
            exec(trys, storage)
        except Exception as e:
            print("Error:", e)
    os.system('cls')

def inputs():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tIn Python, the input() function is a built-in function used to capture user input from the console.")
    typewriter("\tWhen the input() function is called, the program pauses and waits for the user to type something.")
    typewriter("\tThe user\'s input is then returned as a string, regardless of whether the user enters a number, word,")
    typewriter("\tor sentence. You can provide an optional prompt message inside the input() function to guide the user")
    typewriter("\ton what to enter.")
    time.sleep(1)
    typewriter("\n\tEXAMPLE:\n\t\tinput(\"Enter your name here: \")\n\t\tinput(\"Enter your age here: \")")
    time.sleep(1)
    typewriter("\n\tand then it will display \"Enter your name here: \" in the console, and then wait for the user to")
    typewriter("\ttype their name. Once the user presses Enter, the input is returned as a string and can be stored")
    typewriter("\tin a variable for further use.")
    time.sleep(.5)
    typewriter("\nNow I will show you how input works in python")
    input("\npress enter to continue: ")
    typewriter("\nINPUT:\n\tinput(\"Enter your name here: \")")
    typewriter("\nOUTPUT:\n\tEnter your name here:")
    input("\npress enter if you are done reading: ")
    os.system('cls')   
    
def operators():
    os.system('cls')
    while True:
        name = input("\nChoose from the selection below :D\n\tA. Arithmetic Operators\n\tB. Comparison Operators\n\tC. Logical Operators\n\tD. Assignment Operators\n\tX. Exit\nType here ---> ").lower()
        if name == 'a':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tArithmetic operators are the tools Python uses to perform basic math. They work just like the operations")
            typewriter("\twe do in everyday calculations. The + operator adds numbers together, while - subtracts one number from")
            typewriter("\tanother. The * operator multiplies, and / divides numbers, always giving a decimal result. Python also")
            typewriter("\tincludes //, called floor division, which divides but removes anything after the decimal, leaving a whole")
            typewriter("\tnumber. The \'%\' operator gives the remainder after dividing two numbers—useful for checking if a number is")
            typewriter("\teven or odd. Finally, the ** operator raises a number to a power, like squaring or cubing. Together, these")
            typewriter("\toperators allow Python to perform almost any type of math you need.")
            time.sleep(1)
            typewriter("\n\tEXAMPLE:")
            print("\t\t|  Operator:\t|  Meaning:\t\t|  Example:\t|  Result:  |")
            time.sleep(.1)
            print("\t\t|     +\t\t|  Addition\t\t|  3 + 2\t|    5\t    |")
            time.sleep(.1)
            print("\t\t|     -\t\t|  Subtraction\t\t|  5 - 3\t|    2\t    |")
            time.sleep(.1)
            print("\t\t|     *\t\t|  Multiplication\t|  4 * 2\t|    8\t    |")
            time.sleep(.1)
            print("\t\t|     /\t\t|  Division\t\t|  5 / 2\t|   2.5\t    |")
            time.sleep(.1)
            print("\t\t|     //\t|  Floor division\t|  5 // 2\t|    2\t    |")
            time.sleep(.1)
            print("\t\t|     %\t\t|  Modulus (remainder)\t|  5 % 2\t|    1\t    |")
            time.sleep(.1)
            print("\t\t|     **\t|  Exponent\t\t|  2 ** 3\t|    8\t    |")
            time.sleep(.5)
            input("\npress enter if you are done reading: ")
            os.system('cls')
        elif name == 'b':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tComparison operators help Python compare two values and decide whether something is true or false. They")
            typewriter("\tdon\'t give numerical answers—they return either True or False. The == operator checks if two values are")
            typewriter("\tequal, while != checks if they are different. The > and < operators check if one value is greater or")
            typewriter("\tsmaller than another. Their partners, >= and <=, include equality as well, meaning they check for \"greater")
            typewriter("\tor equal\" or \"less or equal.\" These operators are essential when writing conditions, such as deciding if")
            typewriter("\ta user passed a test score or if a number fits within a certain range.")
            time.sleep(1)
            typewriter("\n\tEXAMPLE:")
            print("\t|  Operator:\t|  Meaning:\t\t|  Example:\t|  Result:  |")
            time.sleep(.1)
            print("\t|     ==\t|  Equals\t\t|  5 == 5\t|   true    |")
            time.sleep(.1)
            print("\t|     !=\t|  Not equal\t\t|  5 != 3\t|   true    |")
            time.sleep(.1)
            print("\t|     >\t\t|  Greater than\t\t|  5 > 3\t|   true    |")
            time.sleep(.1)
            print("\t|     <\t\t|  Less than\t\t|  3 < 5\t|   true    |")
            time.sleep(.1)
            print("\t|     >=\t|  Greater or equal\t|  5 >= 5\t|   true    |")
            time.sleep(.1)
            print("\t|     <=\t|  Less or equal\t|  3 <= 5\t|   true    |")
            time.sleep(.5)
            input("\npress enter if you are done reading: ")
            os.system('cls')
        elif name == 'c':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tLogical operators combine multiple conditions to make more complex decisions in Python. The and operator")
            typewriter("\tchecks if both conditions are true before the whole expression becomes true. The or operator is more")
            typewriter("\tflexible it becomes true if at least one condition is true. The not operator acts as a reverser: it flips")
            typewriter("\ta true value to false, and false to true. Logical operators are especially useful when you want Python")
            typewriter("\tto make decisions based on several factors at once, like checking if someone is both over 18 and has an")
            typewriter("\tID, or if a number is either too high or too low.")
            time.sleep(1)
            typewriter("\n\tEXAMPLE:")
            print("\t|  Operator:\t|  Meaning:\t\t\t\t|  Example:\t\t|  Result:  |")
            time.sleep(.1)
            print("\t|     and\t|  True if both are true\t\t|  True and False\t|   false   |")
            time.sleep(.1)
            print("\t|     or\t|  True if at least one is true\t\t|  True or False\t|   true    |")
            time.sleep(.1)
            print("\t|     not\t|  Reverse boolean value\t\t|  not True\t\t|   false   |")
            time.sleep(.5)
            input("\npress enter if you are done reading: ")
            os.system('cls')
        elif name == 'd':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tAssignment operators are used to store values inside variables. The most basic one is =, which simply")
            typewriter("\tassigns a value, like x = 10. Python also provides shortcuts for updating existing values. For example,")
            typewriter("\t+= means \"add something to the existing value,\" so x += 5 is the same as x = x + 5. The same pattern")
            typewriter("\tworks for subtraction (-=), multiplication (*=), division (/=), and the other arithmetic types. These")
            typewriter("\tshortcuts make your code cleaner and faster to write, especially when updating variables repeatedly,")
            typewriter("\tsuch as increasing a score or counting loops.")
            time.sleep(1)
            typewriter("\n\tEXAMPLE:")
            print("\t|  Operator:\t|  Example:\t|  Equivalent To:  |")
            time.sleep(.1)
            print("\t|     =\t\t|  x = 5\t|   Assign 5\t   |")
            time.sleep(.1)
            print("\t|     +=\t|  x += 3\t|   x = x + 3      |")
            time.sleep(.1)
            print("\t|     -=\t|  x -= 3\t|   x = x - 3      |")
            time.sleep(.1)
            print("\t|     *=\t|  x *= 3\t|   x = x * 3      |")
            time.sleep(.1)
            print("\t|     /=\t|  x /= 3\t|   x = x / 3      |")
            time.sleep(.1)
            print("\t|     //=\t|  x //= 3\t|   x = x // 3     |")
            time.sleep(.1)
            print("\t|     %=\t|  x %= 3\t|   x = x % 3      |")
            time.sleep(.1)
            print("\t|     **=\t|  x **= 3\t|   x = x ** 3     |")
            time.sleep(.5)
            input("\npress enter if you are done reading: ")
            os.system('cls')
        elif name == 'x':
            os.system('cls')
            break
        else:
            print("Invalid Input!")
    os.system('cls')

def string_form():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tIt allows you to place variables directly inside a string using {}. This makes output clearer and easier to write.")
    time.sleep(.5)
    typewriter("\n\t\tEXAMPLE:")
    typewriter("\t\t\tname = \"Juan\"")
    typewriter("\t\t\tage = 17")
    typewriter("\t\t\tprint(f\"My name is {name} and I am {age} years old.\")")
    time.sleep(.5)
    typewriter("\n\tHere, Python replaces {name} and {age} with their actual values when the program runs. String formatting")
    typewriter("\tlike this is usually taught under basics, because it is closely related to printing output, strings, and")
    typewriter("\tvariables, which are fundamental concepts needed before moving on to decisions, loops, or functions.")
    input("\npress enter to try: ")
    os.system('cls')
    typewriter("Type \'exit\' if you want to leave.\n")
    time.sleep(2)
    storage = {}
    while True:
        trys = input(">>> ")
        if trys.lower() == "exit":
            typewriter("Exiting compiler...!")
            break   
        try:
            exec(trys, storage)
        except Exception as e:
            print("Error:", e)
    os.system('cls')

def decs_exple():
    print("EXPLANATION:")
    typewriter("\tPython uses if, elif, and else statements to let your program make decisions. An if statement checks a")
    typewriter("\tcondition, and if that condition is true, Python runs the code inside it. If the condition is false,")
    typewriter("\tPython skips it. When you need to check more than one possible condition, you use elif, which means")
    typewriter("\t\"else if.\" Python goes through each condition in order until one of them is true. If none of the if")
    typewriter("\tconditions are true, the else block runs as the final fallback. This structure allows your program to")
    typewriter("\trespond differently depending on the situation, making your code more flexible and interactive.")

def iff():
    os.system('cls')
    typewriter("\n\tEXAMPLE for if:\n")
    typewriter("\t\tage = 18")
    typewriter("\n\t\tif age >= 18:")
    typewriter("\t\t\tprint(\"You are an adult.\")\n")
    typewriter("\n\tTHE OUTPUT:\n")
    typewriter("\t\tYou are an adult.\n")
    input("press enter to continue: ")

def if_else():
    os.system('cls')
    typewriter("\n\tEXAMPLE for if + else:\n")
    typewriter("\t\tage = 15")
    typewriter("\n\t\tif age >= 18:\n\t\t\tprint(\"You are an adult.\")")
    typewriter("\t\telse:\n\t\t\tprint(\"You are a minor.\")\n")
    typewriter("\n\tTHE OUTPUT:\n")
    typewriter("\t\tYou are a minor.\n")
    input("press enter to continue: ")

def if_elif_else():
    os.system('cls')
    typewriter("\n\tEXAMPLE for if + elif + else:\n")
    typewriter("\t\tscore = 75")
    typewriter("\n\t\tif score >= 90:\n\t\t\tprint(\"Grade: A\")")
    typewriter("\t\telif score >= 80:\n\t\t\tprint(\"Grade: B\")")
    typewriter("\t\telif score >= 70:\n\t\t\tprint(\"Grade: C\")")
    typewriter("\t\telse:\n\t\t\tprint(\"Grade: D or below\")\n")
    typewriter("\tTHE OUTPUT:\n")
    typewriter("\t\tGrade: C\n")
    input("press enter to continue: ")

def for_loop():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA for loop in Python is used when you want to repeat a block of code a specific number of times or when")
    typewriter("\tyou want to go through every item in a sequence, such as a list, a string, or a range of numbers. You can")
    typewriter("\tthink of a for loop like a helper that automatically moves through each item one by one and performs the")
    typewriter("\tsame action for each item. This saves time because you don\'t have to write the same line of code repeatedly")
    typewriter("\tPython does the repetition for you. For loops are especially useful for tasks like printing numbers,")
    typewriter("\tchecking items in a list, or doing actions multiple times without manually counting.")
    time.sleep(1)
    typewriter("\n\tEXAMPLE:\n")
    typewriter("\t\tfor i in range(5):\n\t\t\tprint(i)")
    typewriter("\n\tTHE OUTPUT:\n")
    typewriter("\t\t0")
    typewriter("\t\t1")
    typewriter("\t\t2")
    typewriter("\t\t3")
    typewriter("\t\t4\n")
    input("press enter to continue: ")
    os.system('cls')
    print("For Loop with start, step, stop.")
    print("\nEXPLANATION:")
    typewriter("\tA for loop lets Python repeat code automatically. When you use range() in a for loop, it can take up to")
    typewriter("\t\t- start → where the counting begins")
    typewriter("\t\t- stop → where the counting ends (Python stops before this number)")
    typewriter("\t\t- step → how much the number increases each time")
    time.sleep(1)
    typewriter("\n\tEXAMPLE:\n")
    typewriter("\t\tfor i in range(2, 10, 2):\n\t\t\tprint(i)")
    typewriter("\n\tEXPLANATION:")
    typewriter("\t\tstart = 2 → the loop begins at 2")
    typewriter("\t\tstop = 10 → the loop stops before 10")
    typewriter("\t\tstep = 2 → it jumps by 2 each time")
    typewriter("\n\tTHE OUTPUT:\n")
    typewriter("\t\t2")
    typewriter("\t\t4")
    typewriter("\t\t6")
    typewriter("\t\t8\n")
    input("press enter when you are done reading: ")
    os.system('cls')

def while_loop():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA while loop repeats code as long as a condition is true. You start with a value, check the condition, and")
    typewriter("\tupdate the value each time. The loop stops automatically when the condition becomes false. It\'s useful when")
    typewriter("\tyou don\'t know in advance how many times you need to repeat something, like asking a user until they give")
    typewriter("\tthe right answer or counting numbers up to a limit.")
    typewriter("\n\tEXAMPLE:\n")
    typewriter("\t\tbake = True\n\t\twhile bake == True:")
    typewriter("\t\t\tnum = input(\"Do you still want to bake a cake? [yes/no] \").lower()\n\t\t\tif num == 'yes':")
    typewriter("\t\t\t\tprint(\"Your cake is cooking.....\")\n\t\t\t\tcontinue")
    typewriter("\t\t\telse:\n\t\t\t\tprint(\"your cake is done!!\")\n\t\t\t\tbreak")
    typewriter("\n\tTHE OUTPUT:\n")
    typewriter("\t\tDo you still want to bake a cake? [yes/no] yes\n\t\tYour cake is cooking.....")
    typewriter("\t\tDo you still want to bake a cake? [yes/no] yes\n\t\tYour cake is cooking.....")
    typewriter("\t\tDo you still want to bake a cake? [yes/no] no\n\t\tyour cake is done!!")
    typewriter("\n\tEXPLANATION:")
    typewriter("\t\tbake = True → This allows the while loop to start.")
    typewriter("\t\twhile bake == True: → The loop will keep running until break is called.")
    typewriter("\t\tnum = input(...).lower() → The program asks the user to type \"yes\" or \"no\" and converts it to lowercase.")
    typewriter("\t\tif num == 'yes':\n\t\t\t- If the user types yes, it prints \"Your cake is cooking.....\" and continue makes the loop go back to the start.")
    typewriter("\t\telse:\n\t\t\t- If the user types anything other than yes (like no), it prints \"your cake is done!!\" and break stops the loop.")
    input("\npress enter when you are done reading: ")
    os.system('cls')

def loop_control():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tIn Python, loop controls are special statements that let you change the behavior of a loop while it\'s running.")
    typewriter("\tThey help you skip steps, stop the loop early, or do nothing for a particular iteration. There are three main")
    typewriter("\tloop control statements:")
    time.sleep(1)
    typewriter("\n\tSummary Table:\n")
    print("\t\t|  Loop Control  |  What it Does \t\t|")
    time.sleep(.1)
    print("\t\t|   break\t |  Stops the loop immediately  |")
    time.sleep(.1)
    print("\t\t|   continue\t |  Skips current iteratio      |")
    time.sleep(.1)
    print("\t\t|   pass \t |  Does nothing (placeholder)  |")
    typewriter("\nNow I will show you some examples how do we use this loop controls in Python.")
    time.sleep(3)
    input("press enter to continue: ")
    os.system('cls')
    typewriter("Simple break Example:\n")
    typewriter("\ti = 1\n\twhile i <= 5:")
    typewriter("\t\tif i == 3:\n\t\t\tbreak")
    typewriter("\t\tprint(i)\n\t\ti += 1")
    typewriter("\nTHE OUTPUT:\n")
    typewriter("\t1")
    typewriter("\t2")
    time.sleep(2)
    typewriter("\nSimple continue Example:\n")
    typewriter("\ti = 0\n\twhile i < 5:")
    typewriter("\t\ti += 1\n\t\tif i == 3:\n\t\t\tcontinue")
    typewriter("\t\tprint(i)")
    typewriter("\nTHE OUTPUT:\n")
    typewriter("\t1")
    typewriter("\t2")
    typewriter("\t4")
    typewriter("\t5")
    time.sleep(2)
    typewriter("\nSimple pass Example:\n")
    typewriter("\ti = 1\n\twhile i <= 5:")
    typewriter("\t\tif i == 3:\n\t\t\tpass")
    typewriter("\t\tprint(i)\n\t\ti += 1")
    typewriter("\nTHE OUTPUT:\n")
    typewriter("\t1")
    typewriter("\t2")
    typewriter("\t3")
    typewriter("\t4")
    typewriter("\t5")
    time.sleep(2)
    input("\npress enter when you are done reading: ")
    os.system('cls')

def summ_list():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA list in Python is a collection that allows you to store multiple items in a single variable. The items")
    typewriter("\tare kept in a specific order, and you can change the list anytime by adding, removing, or updating elements.")
    typewriter("\tLists are very flexible—you can store numbers, words, or even other lists inside them.")
    time.sleep(1)
    print("\nSUMMARY TABLE:")
    print("\t|  Type:\t|  Ordered?:\t|  Mutable?:\t|  Unique Items?:  |  Example:\t|")
    time.sleep(.1)
    print("\t|   List\t|   Yes\t\t|   Yes\t\t|   No\t\t   |  [1,2,3]\t|")
    time.sleep(.1)
    print("\t|   Tuple\t|   Yes\t\t|   No\t\t|   No\t\t   |   (1,2)\t|")
    time.sleep(.1)
    print("\t|   Set\t\t|   No\t\t|   Yes\t\t|   Yes\t\t   |  {1,2,3}\t|")
    time.sleep(.1)
    print("\t|   Dictionary\t|   Yes\t\t|   Yes\t\t|   Yes\t\t   |  {\"a\":1}\t|")
    time.sleep(2)
    input("\npress enter when you are done reading: ")
    os.system('cls')

def listss():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA list is like a container where you can store many items in a specific order.")
    typewriter("\tYou can add, remove, or change the items anytime.")
    typewriter("\tLists can also contain duplicates (same value can appear more than once).")
    time.sleep(1)
    typewriter("\nNow I will show you how to use list in python")
    input("\npress enter to continue: ")
    typewriter("\nINPUT:\n\tmy_list = [\"apple\", \"banana\", \"cherry\"]\n\n\tprint(my_list)")
    typewriter("\nOUTPUT:\n\t['apple', 'banana', 'cherry']")
    typewriter("\nnow I will show you what are the methos for list in python")
    input("\npress enter to continue: ")
    typewriter("list can changed, so they have many methods to help you manage them.")
    print("LIST METHODS:")
    print("\t|  Method:\t\t|      What it does?:\t\t\t|    Example:\t\t\t\t|")
    time.sleep(.1)
    print("\t|  append()\t\t|  Adds an item at the end\t\t|  fruits.append(\"mango\")\t\t|")
    time.sleep(.1)
    print("\t|  insert()\t\t|  Adds an item at a specific position\t|  fruits.insert(1, \"orange\")\t\t|")
    time.sleep(.1)
    print("\t|  remove()\t\t|  Removes a specific item\t\t|  fruits.remove(\"apple\")\t\t|")
    time.sleep(.1)
    print("\t|  pop()\t\t|  Removes an item by index\t\t|  fruits.pop(0)\t\t\t|")
    time.sleep(.1)
    print("\t|  clear()\t\t|  Removes all items\t\t\t|  fruits.clear()\t\t\t|")
    time.sleep(.1)
    print("\t|  sort()\t\t|  Sorts the list\t\t\t|  numbers.sort()\t\t\t|")
    time.sleep(.1)
    print("\t|  reverse()\t\t|  Reverses the order\t\t\t|  numbers.reverse()\t\t\t|")
    time.sleep(.1)
    print("\t|  extend()\t\t|  Adds all items from another list\t|  fruits.extend([\"kiwi\", \"grape\"])\t|")
    time.sleep(.1)
    input("\npress enter to try these methods: ")
    os.system('cls')
    typewriter("Type \'exit\' if you want to leave.\n")
    time.sleep(2)
    storage = {}
    while True:
        trys = input(">>> ")
        if trys.lower() == "exit":
            typewriter("Exiting compiler...!")
            break   
        try:
            exec(trys, storage)
        except Exception as e:
            print("Error:", e)
    os.system('cls')

def tuplesss():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA tuple is like a list, but it is locked.")
    typewriter("\tOnce you create it, you cannot modify its items.")
    typewriter("\tIt is used when you want the data to stay safe and unchanged.")
    time.sleep(1)
    typewriter("\nNow I will show you how to use tuple in python")
    input("\npress enter to continue: ")
    typewriter("\nINPUT:\n\tcolors = (\"red\", \"blue\", \"green\")\n\n\tprint(\"First color:\", colors[0])\n\tprint(\"Second color:\", colors[1])")
    typewriter("\nOUTPUT:\n\tFirst color: red\n\tSecond color: blue")
    typewriter("\nnow I will show you what are the methos for tuple in python")
    input("\npress enter to continue: ")
    typewriter("Tuples cannot be changed, so they have only 2 methods:")
    print("TUPLE METHODS:")
    print("\t|  Method:\t|      What it does?:\t\t\t\t|    Example:\t\t|")
    time.sleep(.1)
    print("\t|  count()\t|  Counts how many times a value appears\t|  numbers.count(3)\t|")
    time.sleep(.1)
    print("\t|  index()\t|  Finds the position of a value\t\t|  numbers.index(10)\t|")
    time.sleep(.1)
    input("\npress enter to try these methods: ")
    os.system('cls')
    typewriter("Type \'exit\' if you want to leave.\n")
    time.sleep(2)
    storage = {}
    while True:
        trys = input(">>> ")
        if trys.lower() == "exit":
            typewriter("Exiting compiler...!")
            break   
        try:
            exec(trys, storage)
        except Exception as e:
            print("Error:", e)
    os.system('cls')

def setss():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA set is a collection that stores unique items without any specific order.")
    typewriter("\tIt automatically removes duplicates, so each item appears only once.")
    typewriter("\tSets are useful when you want to keep track of distinct values.")
    time.sleep(1)
    typewriter("\nNow I will show you how to use set in python")
    input("\npress enter to continue: ")
    typewriter("\nINPUT:\n\tmy_set = {1, 2, 3, 2, 1}\n\n\tprint(my_set)")
    typewriter("\nOUTPUT:\n\t{1, 2, 3}")
    typewriter("\nnow I will show you what are the methos for set in python")
    input("\npress enter to continue: ")
    typewriter("Sets have several methods to help you manage them.")
    print("SET METHODS:")
    print("\t|     Method:\t\t|      What it does?:\t\t\t  |    Example:\t\t  |")
    time.sleep(.1)
    print("\t|     add()\t\t|  Adds an item\t\t\t\t  |  myset.add(4)\t  |")
    time.sleep(.1)
    print("\t|     remove()\t\t|  Removes an item (error if not found)\t  |  myset.remove(2)\t  |")
    time.sleep(.1)
    print("\t|     discard()\t\t|  Removes an item (no error if missing)  |  myset.discard(10)\t  |")
    time.sleep(.1)
    print("\t|     pop()\t\t|  Removes a random item\t\t  |  myset.pop()\t  |")
    time.sleep(.1)
    print("\t|     clear()\t\t|  Removes all items\t\t\t  |  myset.clear()\t  |")
    time.sleep(.1)
    print("\t|     update()\t\t|  Adds multiple items\t\t\t  |  myset.update([5, 6]) |")
    time.sleep(.1)
    print("\t|     union()\t\t|  Combines sets\t\t\t  |  a.union(b)\t\t  |")
    time.sleep(.1)
    print("\t|     intersection()\t|  Common items\t\t\t\t  |  a.intersection(b)\t  |")
    time.sleep(.1)
    print("\t|     difference()\t|  Items not in another set\t\t  |  a.difference(b)\t  |")
    time.sleep(.1)
    input("\npress enter to try these methods: ")
    os.system('cls')
    typewriter("Type \'exit\' if you want to leave.\n")
    time.sleep(2)
    storage = {}
    while True:
        trys = input(">>> ")
        if trys.lower() == "exit":
            typewriter("Exiting compiler...!")
            break   
        try:
            exec(trys, storage)
        except Exception as e:
            print("Error:", e)
    os.system('cls')

def dictss():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tA dictionary in Python is a collection that stores data in key-value pairs.")
    typewriter("\tEach key is unique and is used to access its corresponding value.")
    typewriter("\tDictionaries are useful for organizing and retrieving data quickly.")
    time.sleep(1)
    typewriter("\nNow I will show you how to use dictionary in python")
    input("\npress enter to continue: ")
    typewriter("\nINPUT:\n\tmy_dict = {\"name\": \"Alice\", \"age\": 25}\n\n\tprint(\"Name:\", my_dict[\"name\"])\n\tprint(\"Age:\", my_dict[\"age\"])")
    typewriter("\nOUTPUT:\n\tName: Alice\n\tAge: 25")
    typewriter("\nnow I will show you what are the methos for dictionary in python")
    input("\npress enter to continue: ")
    typewriter("Dictionaries have several methods to help you manage them.")
    print("DICTIONARY METHODS:")
    print("\t|  Method:\t|      What it does?:\t\t\t  |    Example:\t\t\t  |")
    time.sleep(.1)
    print("\t|  get()\t|  Gets a value safely\t\t\t  |  student.get(\"age\")\t\t  |")
    time.sleep(.1)
    print("\t|  keys()\t|  Returns all keys\t\t\t  |  student.keys()\t\t  |")
    time.sleep(.1)
    print("\t|  values()\t|  Returns all values\t\t\t  |  student.values()\t\t  |")
    time.sleep(.1)
    print("\t|  items()\t|  Returns key-value pairs\t\t  |  student.items()\t\t  |")
    time.sleep(.1)
    print("\t|  update()\t|  Updates dictionary\t\t\t  |  student.update({\"age\": 23})  |")
    time.sleep(.1)
    print("\t|  pop()\t|  Removes a key and returns its value\t  |  student.pop(\"age\")\t\t  |")
    time.sleep(.1)
    print("\t|  clear()\t|  Removes everything\t\t\t  |  student.clear()\t\t  |")
    time.sleep(.1)
    print("\t|  popitem()\t|  Removes last added pair\t\t  |  student.popitem()\t\t  |")
    time.sleep(.1)
    input("\npress enter to try these methods: ")
    os.system('cls')
    typewriter("Type \'exit\' if you want to leave.\n")
    time.sleep(2)
    storage = {}
    while True:
        trys = input(">>> ")
        if trys.lower() == "exit":
            typewriter("Exiting compiler...!")
            break
        try:
            exec(trys, storage)
        except Exception as e:
            print("Error:", e)
    os.system('cls')

def built_in():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tBuilt-in functions are functions that already exist in Python, so you don\'t have to write")
    typewriter("\tthem yourself. You can use them anytime to perform common tasks, like displaying text,")
    typewriter("\tcounting items, converting data types, or doing calculations.")
    time.sleep(1)
    print("\nCOMMON BUILT-IN FUNCTIONS:")
    print("\t|  Functions:\t|      What it does?:\t\t  |    Example:\t\t     |")
    time.sleep(.1)
    print("\t|   print()\t|  Displays text\t\t  |  print(\"Hello\")\t     |")
    time.sleep(.1)
    print("\t|   len()\t|  Counts items\t\t\t  |  len(\"hello\")\t     |")
    time.sleep(.1)
    print("\t|   type()\t|  Shows data type\t\t  |  type(5)\t\t     |")
    time.sleep(.1)
    print("\t|   int()\t|  Converts to integer\t\t  |  int(\"10\")\t\t     |")
    time.sleep(.1)
    print("\t|   float()\t|  Converts to float\t\t  |  float(\"3.14\")\t     |")
    time.sleep(.1)
    print("\t|   str()\t|  Converts to string\t\t  |  str(100)\t\t     |")
    time.sleep(.1)
    print("\t|   range()\t|  Creates a sequence of numbers  |  range(5)\t\t     |")
    time.sleep(.1)
    print("\t|   input()\t|  Takes user input\t\t  |  name = input(\"Name: \")  |")
    time.sleep(.1)
    print("\t|   sum()\t|  Adds all numbers in a list\t  |  sum([1,2,3])\t     |")
    time.sleep(.1)
    print("\t|   max()\t|  Largest value\t\t  |  max([3,7,1])\t     |")
    time.sleep(.1)
    print("\t|   min()\t|  Smallest value\t\t  |  min([3,7,1])\t     |")
    time.sleep(2)
    input("\npress enter when you are done reading: ")
    os.system('cls')

def user_def():
    os.system('cls')
    typewriter("In User-Defined Functions there are two types, the one is a Function without a return value")
    typewriter("and the second is a Function with return value")
    time.sleep(.5)
    while True:
        name = input("\nChoose from the selection below :D\n\tA. Function without a return value\n\tB. Function with return value\n\tX. Exit\nType here ---> ").lower()
        if name == 'a':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tA function without a return value is a type of function that performs an action but does not give back any")
            typewriter("\tresult. For example, a function that simply prints information on the screen is considered a non-returning")
            typewriter("\tfunction. In Python, you can write something like def show_details(): and inside it put print statements")
            typewriter("\tsuch as print(\"Name: Mark\") and print(\"Course: BSIT\"). When you call show_details(), it will display")
            typewriter("\tthe texts, but it will not return any value that you can store in a variable.")
            time.sleep(1)
            typewriter("\nEXAMPLE INPUT:\n\tdef student_info():\n\t\tprint(\"Name: Mark Andrei Alba\")\n\t\tprint(\"Course: BSIT\")\n\n\tstudent_info()")
            typewriter("\nOUTPUT:\n\tName: Mark Andrei Alba\n\tCourse: BSIT")
            input("\npress enter when you are done reading: ")
            os.system('cls')
        elif name == 'b':
            os.system('cls')
            print("EXPLANATION:")
            typewriter("\tA function with a return value is a type of function that processes something and then sends back a result")
            typewriter("\tusing the return keyword. For example, if you create a function like def add(a, b): return a + b, the")
            typewriter("\tfunction will take the two numbers, add them, and return the answer. When you call it using result =")
            typewriter("\tadd(5, 3), the returned value 8 is stored in the variable result, and you can use it anywhere in your")
            typewriter("\tprogram. This type of function is useful when you want to compute something, get an output, and reuse")
            typewriter("\tthat output later in your code.")
            time.sleep(1)
            typewriter("\nEXAMPLE INPUT:\n\tdef add(a, b):\n\t\treturn a + b\")\n\n\tresult = add(4, 5)\n\tprint(result)")
            typewriter("\nOUTPUT:\n\t9")
            input("\npress enter when you are done reading: ")
            os.system('cls')
        elif name == 'x':
            os.system('cls')
            break
        else:
            print("Invalid Input!")

def maths():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tThe math module gives you tools for mathematical operations like square root, powers, pi, etc.")
    time.sleep(.5)
    typewriter("\n\tEXAMPLE:")
    typewriter("\t\timport math")
    typewriter("\n\t\tprint(math.sqrt(25))   # finds square root")
    typewriter("\t\tprint(math.pi)         # prints the value of pi")
    typewriter("\nReminder that the '#' sign is used for writing comments that Python will skip.")
    typewriter("\nHere are the methods in math module:")
    typewriter("\n\t--> math.sqrt(x) - square root")
    typewriter("\t--> math.pow(a, b) - a raised to b")
    typewriter("\t--> math.factorial(x) - factorial of x")
    typewriter("\t--> math.pi - value of pi")
    input("\npress enter when you are done reading: ")
    os.system('cls')

def randoms():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tThe random module is used to generate random numbers. Useful for games, simulations, and testing.")
    time.sleep(.5)
    typewriter("\n\tEXAMPLE:")
    typewriter("\t\timport random")
    typewriter("\n\t\tprint(random.randint(1, 10))  # random number from 1 to 10")
    typewriter("\nReminder that the '#' sign is used for writing comments that Python will skip.")
    typewriter("\nHere are the methods in random module:")
    typewriter("\n\t--> random.randint(a, b) - random number from a to b")
    typewriter("\t--> random.choice(list) - picks random item from a list")
    typewriter("\t--> random.shuffle(list) - mixes list order randomly")
    typewriter("\t--> random.random() - random number between 0 and 1")
    input("\npress enter when you are done reading: ")
    os.system('cls')

def datetimes():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tThe datetime module helps you work with dates and time, like getting the current day or formatting time.")
    time.sleep(.5)
    typewriter("\n\tEXAMPLE:")
    typewriter("\t\timport datetime")
    typewriter("\n\t\tnow = datetime.datetime.now()")
    typewriter("\t\tprint(now)  # shows current date and time")
    typewriter("\nReminder that the '#' sign is used for writing comments that Python will skip.")
    typewriter("\nHere are the methods in datetime module:")
    typewriter("\n\t--> datetime.datetime.now() - current date & time")
    typewriter("\t--> datetime.date.today() - today\'s date")
    typewriter("\t--> strftime() - formats date/time into a string")
    input("\npress enter when you are done reading: ")
    os.system('cls')

def osss():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tThe os module lets your Python program talk to the operating system—like opening folders, checking files, etc.")
    time.sleep(.5)
    typewriter("\n\tEXAMPLE:")
    typewriter("\t\timport os")
    typewriter("\n\t\tprint(os.listdir())  # shows files and folders in the current directory")
    typewriter("\nReminder that the '#' sign is used for writing comments that Python will skip.")
    typewriter("\nHere are the methods in os module:")
    typewriter("\n\t--> os.listdir() - list files in folder")
    typewriter("\t--> os.mkdir(name) - create a folder")
    typewriter("\t--> os.remove(file) - delete file")
    typewriter("\t--> os.getcwd() - get current directory")
    input("\npress enter when you are done reading: ")
    os.system('cls')

def sysss():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tThe sys module gives information about the system running Python. You can access things like")
    typewriter("\tthe Python version or command-line arguments.")
    time.sleep(.5)
    typewriter("\n\tEXAMPLE:")
    typewriter("\t\timport sys")
    typewriter("\n\t\tprint(sys.version)  # shows Python versiont")
    typewriter("\nReminder that the '#' sign is used for writing comments that Python will skip.")
    typewriter("\nHere are the methods in sys module:")
    typewriter("\n\t--> sys.version - shows Python version")
    typewriter("\t--> sys.argv - command-line arguments")
    typewriter("\t--> sys.exit() - exits program")
    input("\npress enter when you are done reading: ")
    os.system('cls')

def statistics():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tThe statistics module helps you compute mean, median, mode, and other statistical numbers.")
    time.sleep(.5)
    typewriter("\n\tEXAMPLE:")
    typewriter("\t\timport statistics")
    typewriter("\n\t\tdata = [2, 4, 6, 8]")
    typewriter("\t\tprint(statistics.mean(data))  # average of the list")
    typewriter("\nReminder that the '#' sign is used for writing comments that Python will skip.")
    typewriter("\nHere are the methods in statistics module:")
    typewriter("\n\t--> statistics.mean() - average")
    typewriter("\t--> statistics.median() - middle value")
    typewriter("\t--> statistics.mode() - most frequent value")
    typewriter("\t--> statistics.stdev() - standard deviation")
    input("\npress enter when you are done reading: ")
    os.system('cls')

def jsons():
    os.system('cls')
    print("EXPLANATION:")
    typewriter("\tThe json module is used to read or write JSON data, which is commonly used for data storage.")
    time.sleep(.5)
    typewriter("\n\tEXAMPLE:")
    typewriter("\t\timport json")
    typewriter("\n\t\tperson = '{\"name\": \"Mark\", \"age\": 20}'")
    typewriter("\t\tdata = json.loads(person)  # convert JSON string to Python dictionary")
    typewriter("\t\tprint(data[\"name\"])")
    typewriter("\nReminder that the '#' sign is used for writing comments that Python will skip.")
    typewriter("\nHere are the methods in json module:")
    typewriter("\n\t--> json.loads() - JSON → Python")
    typewriter("\t--> json.dumps() - Python → JSON")
    input("\npress enter when you are done reading: ")
    os.system('cls')

def sumbless():
    os.system('cls')
    typewriter("SUMMARY TABLE FOR MODULES:")
    print("\n\t======================================================================================================================")
    time.sleep(.1)
    print("\t|  Module:\t|  What It Does?:\t\t\t|  Common Methods:\t\t|  Example Usage:\t     |")
    time.sleep(.1)
    print("\t======================================================================================================================")
    time.sleep(.1)
    print("\t|  math\t\t|  Math operations (square root, pi,\t|  sqrt(), pow(),\t\t|  math.sqrt(25)\t     |")
    time.sleep(.1)
    print("\t|\t\t|  rounding)\t\t\t\t|  factorial(), pi\t\t|\t\t\t     |")
    time.sleep(.1)
    print("\t======================================================================================================================")
    time.sleep(.1)
    print("\t|  random\t| Generates random values\t\t|  randint(), choice(),\t\t|  random.randint(1, 10)     |")
    time.sleep(.1)
    print("\t|\t\t|\t\t\t\t\t|  shuffle(), random()\t\t|\t\t\t     |")
    time.sleep(.1)
    print("\t======================================================================================================================")
    time.sleep(.1)
    print("\t|  datetime\t|  Works with dates and time\t\t|  date.today(), strftime(),\t|  datetime.datetime.now()   |")
    time.sleep(.1)
    print("\t|\t\t|\t\t\t\t\t|  datetime.now()\t\t|\t\t\t     |")
    time.sleep(.1)
    print("\t======================================================================================================================")
    time.sleep(.1)
    print("\t|  os\t\t|  Interacts with files and folders\t|  listdir(), mkdir(),\t\t|  os.listdir()\t\t     |")
    time.sleep(.1)
    print("\t|\t\t|\t\t\t\t\t|  remove(), getcwd()\t\t|\t\t\t     |")
    time.sleep(.1)
    print("\t======================================================================================================================")
    time.sleep(.1)
    print("\t|  sys\t\t|  Gives system-related info\t\t|  version, argv, exit()\t|  sys.version\t\t     |")
    time.sleep(.1)
    print("\t======================================================================================================================")
    time.sleep(.1)
    print("\t|  statistics\t|  Computes statistical values\t\t|  mean(), median(),\t\t|  statistics.mean([1,2,3])  |")
    time.sleep(.1)
    print("\t|\t\t|\t\t\t\t\t|  mode(), stdev()\t\t|\t\t\t     |")
    time.sleep(.1)
    print("\t======================================================================================================================")
    time.sleep(.1)
    print("\t|  json\t\t|  Reads and writes JSON data\t\t|  loads(), dumps()\t\t|  json.loads(text)\t     |")
    time.sleep(.1)
    print("\t======================================================================================================================")
    time.sleep(2)
    input("\npress enter when you are done: ")
    os.system('cls')

def batiti():
    os.system
    typewriter("Wellcome, I am Mark Andrei Alba and now I will show you some of my mini projects that our professor")
    typewriter("gave us during our first sem in Bachelor of Science in Information Technology.")

def code_cha1():
    name = input("Enter your full name: ")
    print("\t\t\t\t\t*\n\t\t\t\t*\t\t*\n\t\t\t*\t\t\t\t*\n\t\t*\t\tHello,\t\t\t\t*\n\t*\t\t\t ", name,"\t\t\t*\n\t\t*\t\t\t\t\t\t*\n\t\t\t*\t\t\t\t*\n\t\t\t\t*\t\t*\n\t\t\t\t\t*")

def code1():
    os.system('cls')
    typewriter("CODE INPUT:")
    typewriter("\n\tname = input(\"Enter your full name: \")")
    typewriter("\tprint(\"\t\t\t\t\t*\n\t\t\t\t*\t\t*\n\t\t\t*\t\t\t\t*\n\t\t*\t\tHello,\t\t\t\t*\n\t*\t\t\t \", name,\"\t\t\t*\n\t\t*\t\t\t\t\t\t*\n\t\t\t*\t\t\t\t*\n\t\t\t\t*\t\t*\n\t\t\t\t\t*\")")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha1()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha2():
    peso = eval(input("Enter amount to deposit --> "))
    print("Here is the breakdown of the deposit amoumt:")
    n1 = peso // 1000
    peso1 = peso % 1000
    n2 = peso1 // 500
    peso2 = peso1 % 500
    n3 = peso2 // 200
    peso3 = peso2 % 200
    n4 = peso3 // 100
    peso4 = peso3 % 100
    n5 = peso4 // 50
    peso5 = peso4 % 50
    n6 = peso5 // 20
    peso6 = peso5 % 20
    n7 = peso6 // 10
    peso7 = peso6 % 10
    n8 = peso7 // 5
    peso8 = peso7 % 5
    n9 = peso8 // 1
    peso9 = peso8 % 1
    print(n1," = 1000")
    print(n2," = 500")
    print(n3," = 200")
    print(n4," = 100")
    print(n5," = 50")
    print(n6," = 20")
    print(n7," = 10")
    print(n8," = 5")
    print(n9," = 1")


def code2():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tpeso = eval(input(\"Enter amount to deposit --> \"))")
    time.sleep(.1)
    print("\tprint(\"Here is the breakdown of the deposit amoumt:\")")
    time.sleep(.1)
    print("\tn1 = peso // 1000")
    time.sleep(.1)
    print("\tpeso1 = peso % 1000")
    time.sleep(.1)
    print("\tn2 = peso1 // 500")
    time.sleep(.1)
    print("\tpeso2 = peso1 % 500")
    time.sleep(.1)
    print("\tn3 = peso2 // 200")
    time.sleep(.1)
    print("\tpeso3 = peso2 % 200")
    time.sleep(.1)
    print("\tn4 = peso3 // 100")
    time.sleep(.1)
    print("\tpeso4 = peso3 % 100")
    time.sleep(.1)
    print("\tn5 = peso4 // 50")
    time.sleep(.1)
    print("\tpeso5 = peso4 % 50")
    time.sleep(.1)
    print("\tn6 = peso5 // 20")
    time.sleep(.1)
    print("\tpeso6 = peso5 % 20")
    time.sleep(.1)
    print("\tn7 = peso6 // 10")
    time.sleep(.1)
    print("\tpeso7 = peso6 % 10")
    time.sleep(.1)
    print("\tn8 = peso7 // 5")
    time.sleep(.1)
    print("\tpeso8 = peso7 % 5")
    time.sleep(.1)
    print("\t n9 = peso8 // 1")
    time.sleep(.1)
    print("\tpeso9 = peso8 % 1")
    time.sleep(.1)
    print("\tprint(n1,\" = 1000\")")
    time.sleep(.1)
    print("\tprint(n2,\" = 500\")")
    time.sleep(.1)
    print("\tprint(n3,\" = 200\")")
    time.sleep(.1)
    print("\tprint(n4,\" = 100\")")
    time.sleep(.1)
    print("\tprint(n5,\" = 50\")")
    time.sleep(.1)
    print("\tprint(n6,\" = 20\")")
    time.sleep(.1)
    print("\tprint(n7,\" = 10\")")
    time.sleep(.1)
    print("\tprint(n8,\" = 5\")")
    time.sleep(.1)
    print("\tprint(n9,\" = 1\")")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha2()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha3():
    name = input("What is your name? --> ")
    fare = eval(input("Magkano bayad mo? --> "))
    tao = input("Are you a student? (yes or no) ")

    if tao.lower() == 'yes':
        percent = fare * .2
        bayad = fare - percent
        print(name, "You are eligible to a student discount \nThis is your discount:", percent ,"\nHere's the total amount:", bayad)
    else:
        print(name,"Sorry, you can't get a fare discount")

def code3():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tname = input(\"What is your name? --> \")")
    print("\tfare = eval(input(\"Magkano bayad mo? --> \"))")
    print("\ttao = input(\"Are you a student? (yes or no) \")")
    print("\n\tif tao.lower() == 'yes':")
    print("\t\tpercent = fare * .2")
    print("\t\tbayad = fare - percent")
    print("\t\tprint(name, \"You are eligible to a student discount \nThis is your discount:\", percent ,\"\nHere's the total amount:\", bayad)")
    print("\telse:")
    print("\t\tprint(name,\"Sorry, you can't get a fare discount\")")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha3()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha4():
    anime = input("Welcome to the world of manga\nI can recommend a manga's that based on your genre\nPlease choose a genre: (Action, Comedy, Romance); ").lower()
    if anime == 'action':
        man1 = input("How long should the manga be? (Short, Medium, Long): ").lower()
        if man1 == 'short':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'All you need is Kill'. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Bakuman'. ")
            else:
                print("The recommendation cannot be proccessed!")
        elif man1 == 'medium':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'Dorohedoro'. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Alice in Borderland'. ")
            else:
                print("The recommendation cannot be proccessed!")
        elif man1 == 'long':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'One Piece'. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Attack on Titan'. ")
            else:
                print("The recommendation cannot be proccessed!")
        else:
            print("The recommendation cannot be proccessed!")
    elif anime == 'comedy':
        man1 = input("How long should the manga be? (Short, Medium, Long): ").lower()
        if man1 == 'short':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'Beck'. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Saint Young Men'. ")
            else:
                print("The recommendation cannot be proccessed!")
        elif man1 == 'medium':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'Astro Boy'. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Arakwwa Under the Bridge'. ")
            else:
                print("The recommendation cannot be proccessed!")
        elif man1 == 'long':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'Gintama'. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Hinamatsuri'. ")
            else:
                print("The recommendation cannot be proccessed!")
        else:
            print("The recommendation cannot be proccessed!")
    elif anime == 'romance':
        man1 = input("How long should the manga be? (Short, Medium, Long): ").lower()
        if man1 == 'short':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'Millennium Snow'. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Dengeki Daisy'. ")
            else:
                print("The recommendation cannot be proccessed!")
        elif man1 == 'medium':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'Eyes' by Katra Masaku. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Kimi ni Todoke: From me to You'. ")
            else:
                print("The recommendation cannot be proccessed!")
        elif man1 == 'long':
            den = input("Which decade? (2000s, 2010s): ").lower()
            if den == '2000':
                print("I highly recommended the manga called 'Skip Beat!' by Yoshiki Nakamura. ")
            elif den == '2010':
                print("I highly recommended the manga called 'Ao Haru Ride'. ")
            else:
                print("The recommendation cannot be proccessed!")
        else:
            print("The recommendation cannot be proccessed!")
    else:
        print("The recommendation cannot be proccessed!")

def code4():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tanime = input(\"Welcome to the world of manga\nI can recommend a manga's that based on your genre\nPlease choose a genre: (Action, Comedy, Romance); \").lower()")
    time.sleep(.1)
    print("\tif anime == 'action':")
    time.sleep(.1)
    print("\t\tman1 = input(\"How long should the manga be? (Short, Medium, Long): \").lower()")
    time.sleep(.1)
    print("\t\tif man1 == 'short':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'All you need is Kill'. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Bakuman'. \")")
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telif man1 == 'medium':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Dorohedoro'. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Alice in Borderland'. \")")
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telif man1 == 'long':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'One Piece'. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Attack on Titan'. \")")
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telse:")
    time.sleep(.1)
    print("\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\telif anime == 'comedy':")
    time.sleep(.1)
    print("\t\tman1 = input(\"How long should the manga be? (Short, Medium, Long): \").lower()")
    time.sleep(.1)
    print("\t\tif man1 == 'short':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Beck'. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Saint Young Men'. \")")
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telif man1 == 'medium':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Astro Boy'. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Arakwwa Under the Bridge'. \")")   
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telif man1 == 'long':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Gintama'. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Hinamatsuri'. \")")
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telse:")
    time.sleep(.1)
    print("\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\telif anime == 'romance':\")")
    time.sleep(.1)
    print("\t\tman1 = input(\"How long should the manga be? (Short, Medium, Long): \").lower()")
    time.sleep(.1)
    print("\t\tif man1 == 'short':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Millennium Snow'. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Dengeki Daisy'. \")")
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telif man1 == 'medium':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Eyes' by Katra Masaku. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Kimi ni Todoke: From me to You'. \")")
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telif man1 == 'long':")
    time.sleep(.1)
    print("\t\t\tden = input(\"Which decade? (2000s, 2010s): \").lower()")
    time.sleep(.1)
    print("\t\t\tif den == '2000':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Skip Beat!' by Yoshiki Nakamura. \")")
    time.sleep(.1)
    print("\t\t\telif den == '2010':")
    time.sleep(.1)
    print("\t\t\t\tprint(\"I highly recommended the manga called 'Ao Haru Ride'. \")")
    time.sleep(.1)
    print("\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\t\telse:")
    time.sleep(.1)
    print("\t\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.1)
    print("\telse:")
    time.sleep(.1)
    print("\t\tprint(\"The recommendation cannot be proccessed!\")")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha4()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha5():
    print("Welcome to the Factor Program!")
    num = 1
    den = eval(input("Enter number:"))
    for a in range(den, 0, -1):
        num *= a
    print("The Factor is ", num)

def code5():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tprint(\"Welcome to the Factor Program!\")")
    time.sleep(.1)
    print("\tnum = 1")
    time.sleep(.1)
    print("\tden = eval(input(\"Enter number:\"))")
    time.sleep(.1)
    print("\tfor a in range(den, 0, -1):")
    time.sleep(.1)
    print("\t\tnum *= a")
    time.sleep(.1)
    print("\tprint(\"The Factor is \", num)")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha5()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha6():
    print("Welcome to the ODD Number Summation!")
    num = 0
    for a in range(1, 11, 1):
        den = eval(input("Enter random number:"))
        if den % 2 == 1:
            num += den
    print("The summation of all add number is", num)

def code6():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tprint(\"Welcome to the ODD Number Summation!\")")
    time.sleep(.1)
    print("\tnum = 0")
    time.sleep(.1)
    print("\tfor a in range(1, 11, 1):")
    time.sleep(.1)
    print("\t\tden = eval(input(\"Enter random number:\"))")
    time.sleep(.1)
    print("\t\tif den % 2 == 1:")
    time.sleep(.1)
    print("\t\t\tnum += den")
    time.sleep(.1)
    print("\tprint(\"The summation of all add number is\", num)")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha6()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha7():
    count = eval(input("COUNTDOWN TIMER SIMULATOR\nEnter the starting number for countdown: "))
    print("Countdown started:")
    import time
    for s in range(count, 0, -1):
        print(s)
        time.sleep(1)
    print("Liftoff!")

def code7():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tcount = eval(input(\"COUNTDOWN TIMER SIMULATOR\nEnter the starting number for countdown: \"))")
    time.sleep(.1)
    print("\tprint(\"Countdown started:\")")
    time.sleep(.1)
    print("\timport time")
    time.sleep(.1)
    print("\tfor s in range(count, 0, -1):")
    time.sleep(.1)
    print("\t\tprint(s)")
    time.sleep(.1)
    print("\t\ttime.sleep(1)")
    time.sleep(.1)
    print("\tprint(\"Liftoff!\")")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha7()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha8():
    number = eval(input("MULTIPLICATION TABLE MAKER\nEnter a number: "))
    print("Multiplication table for",number,":")
    for s in range(1, 11, 1):
        print(number,"x",s,"=",number * s)

def code8():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tnumber = eval(input(\"MULTIPLICATION TABLE MAKER\nEnter a number: \"))")
    time.sleep(.1)
    print("\tprint(\"Multiplication table for\",number,\":\")")
    time.sleep(.1)
    print("\tfor s in range(1, 11, 1):")
    time.sleep(.1)
    print("\t\tprint(number,\"x\",s,\"=\",number * s)")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha8()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha9():
    name = input("🦜PARROT SIMULATOR-THE ECHO CHAMBER!\nWhat do you want your parrot to say?: ")
    many = eval(input("How many times should the parrot squawk it?: "))
    print("Listen to your parrot:")
    for a in range(1, many + 1, 1):
        print("🦜Squawk!",name)

def code9():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tname = input(\"🦜PARROT SIMULATOR-THE ECHO CHAMBER!\nWhat do you want your parrot to say?: \")")
    time.sleep(.1)
    print("\tmany = eval(input(\"How many times should the parrot squawk it?: \"))")
    time.sleep(.1)
    print("\tprint(\"Listen to your parrot:\")")
    time.sleep(.1)
    print("\tfor a in range(1, many + 1, 1):")
    time.sleep(.1)
    print("\t\tprint(\"🦜Squawk!\",name")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha9()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha10():
    for i in range(10, 0, -1):
        for x in range(1,i, 1):
            print("*",end=" ")
        print()

def code10():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tfor i in range(10, 0, -1):")
    time.sleep(.1)
    print("\t\tfor x in range(1,i, 1):")
    time.sleep(.1)
    print("\t\t\tprint("*",end=" ")")
    time.sleep(.1)
    print("\t\tprint()")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha10()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')
    
def code_cha11():
    print("\t\t x",end=" ")
    for drei in range(1,11,1):
        for h in range(10, drei, -1):
            print(" ", end=" ")
        for g in range(1, drei, 1):
            print("x", end=" ")
        for i in range(1, drei,1):
            print("x", end=" ")
        print()

def code11():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tprint(\"\t\t x\",end=\" \")")
    time.sleep(.1)
    print("\tfor drei in range(1,11,1):")
    time.sleep(.1)
    print("\t\tfor h in range(10, drei, -1):")
    time.sleep(.1)
    print("\t\t\tprint(" ", end=" ")")
    time.sleep(.1)
    print("\t\tfor g in range(1, drei, 1):")
    time.sleep(.1)
    print("\t\t\tprint(\"x\", end=\" \")")
    time.sleep(.1)
    print("\t\tfor i in range(1, drei,1):")
    time.sleep(.1)
    print("\t\t\tprint(\"x\", end=\" \")")
    time.sleep(.1)
    print("\t\tprint()")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha11()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha12():
    for drei in range(1,7,1):
        for h in range(7, drei, -1):
            print(" ", end=" ")
        for g in range(drei,0,-1):
            print(g, end=" ")
        for i in range(2,drei+1,1):
            print(i, end=" ")
        print()

def code12():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tfor drei in range(1,7,1):")
    time.sleep(.1)
    print("\t\tfor h in range(7, drei, -1):")
    time.sleep(.1)
    print("\t\t\tprint(" ", end=" ")")
    time.sleep(.1)
    print("\t\tfor g in range(drei,0,-1):")
    time.sleep(.1)
    print("\t\t\tprint(g, end=" ")")
    time.sleep(.1)
    print("\t\tfor i in range(2,drei+1,1):")
    time.sleep(.1)
    print("\t\t\tprint(i, end=" ")")
    time.sleep(.1)
    print("\t\tprint()")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha12()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha13():
    k = input("Enter your name ---> ")
    print("===================================\nODD NUMBER SUMMATION, press 0 to stop\n===================================")
    sum = 0
    odd = ''
    while True:
        den = eval(input("Input a random number ---> "))
        if den == 0:
            print("Program stops .!!!")
            break
        elif den % 2 == 1:
            print("ODD NUMBER DETECTED, code continues")
            sum += den
            odd = str(den) + " "
            continue
        elif den % 2 == 0:
            print("EVEN NUMBER DETECTED, continue")
            continue
    print(f"Hi {k}, the sum of all ODD number is {sum}")
    print(f"ODD numbers detected included the ff {odd}")

def code13():
    os.system('cls')
    typewriter("CODE INPUT:")
    print("\n\tk = input(\"Enter your name ---> \")")
    time.sleep(.1)
    print("\tprint(\"===================================\nODD NUMBER SUMMATION, press 0 to stop\n===================================\")")
    time.sleep(.1)
    print("\tsum = 0")
    time.sleep(.1)
    print("\todd = ''")
    time.sleep(.1)
    print("\twhile True:")
    time.sleep(.1)
    print("\t\tden = eval(input(\"Input a random number ---> \"))")
    time.sleep(.1)
    print("\t\tif den == 0:")
    time.sleep(.1)
    print("\t\t\tprint(\"Program stops .!!!\")")
    time.sleep(.1)
    print("\t\t\tbreak")
    time.sleep(.1)
    print("\t\telif den % 2 == 1:")
    time.sleep(.1)
    print("\t\t\tprint(\"ODD NUMBER DETECTED, code continues\")")
    time.sleep(.1)
    print("\t\t\tsum += den")
    time.sleep(.1)
    print("\t\t\todd = str(den) + " "")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\t\telif den % 2 == 0:")
    time.sleep(.1)
    print("\t\t\tprint(\"EVEN NUMBER DETECTED, continue\")")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\tprint(f\"Hi {k}, the sum of all ODD number is {sum}\")")
    time.sleep(.1)
    print("\tprint(f\"ODD numbers detected included the ff {odd}\")")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha13()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def code_cha14():
    import os
    import json

    os.system('cls')

    print('STUDENT INFORMATION SYSTEM')
    print("=======================================")

    # Empty dictionary
    student_record = {}

    while True:
        print("SELECT FOR THE FOLLOWING OPTIONS")
        print("A - ADD STUDENT RECORD")
        print("B - PRINT ALL STUDENT RECORD")
        print("C - SEARCH STUDENT RECORD")
        print("D - DELETE STUDENT RECORD")
        print("E - EDIT STUDENT RECORD")
        print("F - EXPORT STUDENT RECORD")
        print("G - IMPORT STUDENT RECORD")
        print("X - EXIT SYSTEM")
        print("=========================================")
        choice = input("SELECT FROM THE OPTIONS ABOVE ---> ").lower()

        if choice == 'a':
            os.system('cls')
            print("\nADDING STUDENT RECORD")
            id_no = input("Please input student ID number ---> ")
            first_name = input("Please input student First Name ---> ").upper()
            second_name = input("Please input student Second Name ---> ").upper()
            last_name = input("Please input student Last Name ---> ").upper()
            age = eval(input("Input student age ---> "))
            course = input("Input student Course ---> ").upper()
            section = input("Input student Section ---> ").upper()
            student_record[id_no] = [first_name,second_name,last_name, age, course,section]
            print("DATA SAVED SUCCESSFULLY")
            # Go back to the original menu
            continue
        elif choice == 'b':
            os.system('cls')
            print("PRINTING STUDENT RECORD")
            for i, j in student_record.items():
                print(f"STUDENT ID - {i}    |INFORMATION - {j}")
            continue
        elif choice == 'c':
            os.system('cls')
            print("SEARCH STUDENT RECORD")
            search_id = input("Input student id for search --> ").lower()
            for each_id in student_record.keys():
                if each_id in student_record.keys():
                    print("==================================")
                    print(f"\nRECORD FOUND for ID {search_id}")
                    # to print the record for the search id
                    for i in student_record[search_id]:
                        print(f"--- {i}")
                    print("==================================")
                else:
                    print("NO RECORD FOUND")
                break
            continue
        elif choice == 'd':
            os.system('cls')
            print("DELETE STUDENT RECORD")
            search_id = input("Input student id for search --> ").lower()
            for each_id in student_record.keys():
                if each_id in student_record.keys():
                    print("==================================")
                    print(f"\nRECORD FOUND for ID {search_id}")
                    # to print the record for the search id
                    for i in student_record[search_id]:
                        print(f"--- {i}")
                    print("==================================")
                    student_record.pop(search_id)
                    print("\nRECORD DELETE")
                elif search_id != student_record.items():
                    print("NO RECORD FOUND")
                else:
                    print("NO RECORD FOUND")
                break
            continue
        elif choice == 'e':
            os.system('cls')
            print("EDIT/MODIFYG STUDENT RECORD")
            search_id = input("Input student id for search --> ").lower()
            for each_id in student_record.keys():
                if each_id in student_record.keys():
                    print("==================================")
                    print(f"\nRECORD FOUND for ID {search_id}")
                    # to print the record for the search id
                    for i in student_record[search_id]:
                        print(f"--- {i}")
                    print("==================================")
                    # new set of value for searched id
                    first_name = input("Please input student First Name ---> ").upper()
                    second_name = input("Please input student Second Name ---> ").upper()
                    last_name = input("Please input student Last Name ---> ").upper()
                    age = eval(input("Input student age ---> "))
                    course = input("Input student Course ---> ").upper()
                    section = input("Input student Section ---> ").upper()
                    student_record[search_id][0] = first_name
                    student_record[search_id][1] = second_name
                    student_record[search_id][2] = last_name
                    student_record[search_id][3] = age
                    student_record[search_id][4] = course
                    student_record[search_id][5] = section
                else:
                    print("NO RECORD FOUND")
            continue
        elif choice == 'f':
            os.system("cls")
            print("EXPORT STUDENT RECORD")
            # json JavaScript Object Notation
                    # w = write
            with open('student_record.json', 'w') as new_file:
                json.dump(student_record,new_file, indent=4)
            print("EXPORT SUCCESSFUL")
            continue
        elif choice == 'g':
            os.system("cls")
            print("IMPORT STUDENT RECORD")
                    # r = read
            with open('student_record.json', 'r') as new_file:
                imported_student = json.load(new_file)
            student_record = imported_student
            print("IMPORT SUCCESSFUL")
            continue
        elif choice == 'x':
            break
        else:
            print("INVALID CHOICE")
            continue

def code14():
    os.system('cls')
    typewriter("Reminder that the '#' sign is used for writing comments that Python will skip.")
    typewriter("\nCODE INPUT:")
    print("\n\timport os")
    time.sleep(.1)
    print("\timport json")
    time.sleep(.1)
    print("\n\tos.system('cls')")
    time.sleep(.1)
    print("\n\tprint('STUDENT INFORMATION SYSTEM')")
    time.sleep(.1)
    print("\tprint(\"=======================================\")")
    time.sleep(.1)
    print("\n\t# Empty dictionary")
    time.sleep(.1)
    print("\tstudent_record = {}")
    time.sleep(.1)
    print("\n\twhile True:")
    time.sleep(.1)
    print("\t\tprint(\"SELECT FOR THE FOLLOWING OPTIONS\")")
    time.sleep(.1)
    print("\t\tprint(\"A - ADD STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\tprint(\"B - PRINT ALL STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\tprint(\"C - SEARCH STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\tprint(\"D - DELETE STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\tprint(\"E - EDIT STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\tprint(\"F - EXPORT STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\tprint(\"G - IMPORT STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\tprint(\"X - EXIT SYSTEM\")")
    time.sleep(.1)
    print("\t\tprint(\"=========================================\")")
    time.sleep(.1)
    print("\t\tchoice = input(\"SELECT FROM THE OPTIONS ABOVE ---> \").lower()")
    time.sleep(.1)
    print("\n\t\tif choice == 'a':")
    time.sleep(.1)
    print("\t\t\tos.system('cls')")
    time.sleep(.1)
    print("\t\t\tprint(\"\\nADDING STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\t\tid_no = input(\"Please input student ID number ---> \")")
    time.sleep(.1)
    print("\t\t\tfirst_name = input(\"Please input student First Name ---> \").upper()")
    time.sleep(.1)
    print("\t\t\tsecond_name = input(\"Please input student Second Name ---> \").upper()")
    time.sleep(.1)
    print("\t\t\tlast_name = input(\"Please input student Last Name ---> \").upper()")
    time.sleep(.1)
    print("\t\t\tage = eval(input(\"Input student age ---> \"))")
    time.sleep(.1)
    print("\t\t\tcourse = input(\"Input student Course ---> \").upper()")
    time.sleep(.1)
    print("\t\t\tsection = input(\"Input student Section ---> \").upper()")
    time.sleep(.1)
    print("\t\t\tstudent_record[id_no] = [first_name,second_name,last_name, age, course,section]")
    time.sleep(.1)
    print("\t\t\tprint(\"DATA SAVED SUCCESSFULLY\")")
    time.sleep(.1)
    print("\t\t\t# Go back to the original menu")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\t\telif choice == 'b':")
    time.sleep(.1)
    print("\t\t\tos.system('cls')")
    time.sleep(.1)
    print("\t\t\tprint(\"PRINTING STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\t\tfor i, j in student_record.items():")
    time.sleep(.1)
    print("\t\t\t\tprint(f\"STUDENT ID - {i}    |INFORMATION - {j}\")")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\t\telif choice == 'c':")
    time.sleep(.1)
    print("\t\t\tos.system('cls')")
    time.sleep(.1)
    print("\t\t\tprint(\"SEARCH STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\t\tsearch_id = input(\"Input student id for search --> \").lower()")
    time.sleep(.1)
    print("\t\t\tfor each_id in student_record.keys():")
    time.sleep(.1)
    print("\t\t\t\tif each_id in student_record.keys():")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"==================================\")")
    time.sleep(.1)
    print("\t\t\t\t\tprint(f\"\\nRECORD FOUND for ID {search_id}\")")
    time.sleep(.1)
    print("\t\t\t\t\t# to print the record for the search id")
    time.sleep(.1)
    print("\t\t\t\t\tfor i in student_record[search_id]:")
    time.sleep(.1)
    print("\t\t\t\t\t\tprint(f\"--- {i\")")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"==================================\")")
    time.sleep(.1)
    print("\t\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"NO RECORD FOUND\")")
    time.sleep(.1)
    print("\t\t\t\tbreak")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\t\telif choice == 'd':")
    time.sleep(.1)
    print("\t\t\tos.system('cls')")
    time.sleep(.1)
    print("\t\t\tprint(\"DELETE STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\t\tsearch_id = input(\"Input student id for search --> \").lower()")
    time.sleep(.1)
    print("\t\t\tfor each_id in student_record.keys():")
    time.sleep(.1)
    print("\t\t\t\tif each_id in student_record.keys():")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"==================================\")")
    time.sleep(.1)
    print("\t\t\t\t\tprint(f\"\\nRECORD FOUND for ID {search_id}\")")
    time.sleep(.1)
    print("\t\t\t\t\t# to print the record for the search id")
    time.sleep(.1)
    print("\t\t\t\t\tfor i in student_record[search_id]:")
    time.sleep(.1)
    print("\t\t\t\t\t\tprint(f\"--- {i}\")")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"==================================\")")
    time.sleep(.1)
    print("\t\t\t\t\tstudent_record.pop(search_id)")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"\\nRECORD DELETE\")")
    time.sleep(.1)
    print("\t\t\t\telif search_id != student_record.items():")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"NO RECORD FOUND\")")
    time.sleep(.1)
    print("\t\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"NO RECORD FOUND\")")
    time.sleep(.1)
    print("\t\t\t\tbreak")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\t\telif choice == 'e':")
    time.sleep(.1)
    print("\t\t\tos.system('cls')")
    time.sleep(.1)
    print("\t\t\tprint(\"EDIT/MODIFYG STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\t\tsearch_id = input(\"Input student id for search --> \").lower()")
    time.sleep(.1)
    print("\t\t\tfor each_id in student_record.keys():")
    time.sleep(.1)
    print("\t\t\t\tif each_id in student_record.keys():")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"==================================\")")
    time.sleep(.1)
    print("\t\t\t\t\tprint(f\"\\nRECORD FOUND for ID {search_id}\")")
    time.sleep(.1)
    print("\t\t\t\t\t# to print the record for the search id")
    time.sleep(.1)
    print("\t\t\t\t\tfor i in student_record[search_id]:")
    time.sleep(.1)
    print("\t\t\t\t\t\tprint(f\"--- {i}\")")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"==================================\")")
    time.sleep(.1)
    print("\t\t\t\t\t# new set of value for searched id")
    time.sleep(.1)
    print("\t\t\t\t\tfirst_name = input(\"Please input student First Name ---> \").upper()")
    time.sleep(.1)
    print("\t\t\t\t\tsecond_name = input(\"Please input student Second Name ---> \").upper()")
    time.sleep(.1)
    print("\t\t\t\t\tlast_name = input(\"Please input student Last Name ---> \").upper()")
    time.sleep(.1)
    print("\t\t\t\t\tage = eval(input(\"Input student age ---> \")")
    time.sleep(.1)
    print("\t\t\t\t\tcourse = input(\"Input student Course ---> \").upper()")
    time.sleep(.1)
    print("\t\t\t\t\tsection = input(\"Input student Section ---> \").upper()")
    time.sleep(.1)
    print("\t\t\t\t\tstudent_record[search_id][0] = first_name")
    time.sleep(.1)
    print("\t\t\t\t\tstudent_record[search_id][1] = second_name")
    time.sleep(.1)
    print("\t\t\t\t\tstudent_record[search_id][2] = last_name")
    time.sleep(.1)
    print("\t\t\t\t\tstudent_record[search_id][3] = age")
    time.sleep(.1)
    print("\t\t\t\t\tstudent_record[search_id][4] = course")
    time.sleep(.1)
    print("\t\t\t\t\tstudent_record[search_id][5] = section")
    time.sleep(.1)
    print("\t\t\t\telse:")
    time.sleep(.1)
    print("\t\t\t\t\tprint(\"NO RECORD FOUND\")")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\t\telif choice == 'f':")
    time.sleep(.1)
    print("\t\t\tos.system(\"cls\")")
    time.sleep(.1)
    print("\t\t\tprint(\"EXPORT STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\t\t# json JavaScript Object Notation")
    time.sleep(.1)
    print("\t\t\t\t\t# w = write")
    time.sleep(.1)
    print("\t\t\twith open('student_record.json', 'w') as new_file:")
    time.sleep(.1)
    print("\t\t\t\tjson.dump(student_record,new_file, indent=4)")
    time.sleep(.1)
    print("\t\t\tprint(\"EXPORT SUCCESSFUL\")")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\t\t\tos.system(\"cls\")")
    time.sleep(.1)
    print("\t\t\tprint(\"IMPORT STUDENT RECORD\")")
    time.sleep(.1)
    print("\t\t\t\t\t# r = read")
    time.sleep(.1)
    print("\t\t\twith open('student_record.json', 'r') as new_file:")
    time.sleep(.1)
    print("\t\t\t\timported_student = json.load(new_file)")
    time.sleep(.1)
    print("\t\t\tstudent_record = imported_student")
    time.sleep(.1)
    print("\t\t\tprint(\"IMPORT SUCCESSFUL\")")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.1)
    print("\t\telif choice == 'x':")
    time.sleep(.1)
    print("\t\t\tbreak")
    time.sleep(.1)
    print("\t\telse:")
    time.sleep(.1)
    print("\t\t\tprint(\"INVALID CHOICE\")")
    time.sleep(.1)
    print("\t\t\tcontinue")
    time.sleep(.5)
    input("\nPRESS ENTER TO THE CODE OUTPUT:")
    os.system('cls')
    code_cha14()
    time.sleep(2)
    input("press enter to continue! ")
    os.system('cls')

def easyq():
    os.system('cls')
    print("===========================================================================================")
    time.sleep(.3)
    print("================================WELLCOME TO THE PYTHON QUIZ================================")
    time.sleep(.3)
    print("===========================================================================================")
    time.sleep(.3)
    typewriter("\nLEVEL: EASY")
    input("\npress enter when you are ready: ")
    os.system('cls')
    print("===========================================================================================")
    print("================================WELLCOME TO THE PYTHON QUIZ================================")
    print("===========================================================================================")
    typewriter("\nGOODLUCK!")
    score = 0
    answer = input("\n1. What is a variable?\nA. A loop\nB. A place to store data\nC. A function\nD. A condition\nAnswer: ")
    if answer.lower() == "b":
        typewriter("GREAT!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is B. A place to store data")
    answer = input("\n2. Which symbol is used for comments in Python?\nA. //\nB. <!-- -->\nC. #\nD. **\nAnswer: ")
    if answer.lower() == "c":
        typewriter("NICE!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is C. #")
    answer = input("\n3. Which function is used to display output?\nA. input()\nB. show()\nC. print()\nD. display()\nAnswer: ")
    if answer.lower() == "c":
        typewriter("GOOD JOB!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is C. print()")
    answer = input("\n4. Which is a correct variable name?\nA. 1name\nB. my-name\nC. my_name\nD. my name\nAnswer: ")
    if answer.lower() == "c":
        typewriter("VERY GOOD!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is C. my_name")
    answer = input("\n5. What does input() do?\nA. Shows text\nB. Gets user input\nC. Stores output\nD. Ends program\nAnswer: ")
    if answer.lower() == "b":
        typewriter("AWESOME!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is B. Gets user input")
    time.sleep(.5)
    print(f"\nYour final score is {score} / 5")
    time.sleep(.5)
    print("Quiz completed!")
    input("\npress enter to continue: ")
    os.system('cls')

def medq():
    os.system('cls')
    print("===========================================================================================")
    time.sleep(.3)
    print("================================WELLCOME TO THE PYTHON QUIZ================================")
    time.sleep(.3)
    print("===========================================================================================")
    time.sleep(.3)
    typewriter("\nLEVEL: MEDIUM")
    input("\npress enter when you are ready: ")
    os.system('cls')
    print("===========================================================================================")
    print("================================WELLCOME TO THE PYTHON QUIZ================================")
    print("===========================================================================================")
    typewriter("\nGOODLUCK!")
    score = 0
    answer = input("\n1. What is the output?\nx = 5\nprint(x + 3)\nA. 53\nB. 8\nC. x + 3\nD. Error\nAnswer: ")
    if answer.lower() == "b":
        typewriter("GREAT!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is B. 8")
    answer = input("\n2. Which keyword is used for decision-making?\nA. for\nB. while\nC. if\nD. def\nAnswer: ")
    if answer.lower() == "c":
        typewriter("NICE!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is C. if")
    answer = input("\n3. How many times will this loop run?\nfor i in range(3):\n    print(i)\nA. 2\nB. 3\nC. 4\nD. Infinite\nAnswer: ")
    if answer.lower() == "b":
        typewriter("GOOD JOB!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is B. 3t")
    answer = input("\n4. Which is the correct function definition?\nA. function myFunc():\nB. def myFunc:\nC. def myFunc():\nD. define myFunc()\nAnswer: ")
    if answer.lower() == "c":
        typewriter("VERY GOOD!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is C. def myFunc():")
    answer = input("\n5. Which data type stores text?\nA. int\nB. float\nC. str\nD. bool\nAnswer: ")
    if answer.lower() == "c":
        typewriter("AWESOME!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is C. str")
    time.sleep(.5)
    print(f"\nYour final score is {score} / 5")
    time.sleep(.5)
    print("Quiz completed!")
    input("\npress enter to continue: ")
    os.system('cls')

def hardq():
    os.system('cls')
    print("===========================================================================================")
    time.sleep(.3)
    print("================================WELLCOME TO THE PYTHON QUIZ================================")
    time.sleep(.3)
    print("===========================================================================================")
    time.sleep(.3)
    typewriter("\nLEVEL: HARD")
    input("\npress enter when you are ready: ")
    os.system('cls')
    print("===========================================================================================")
    print("================================WELLCOME TO THE PYTHON QUIZ================================")
    print("===========================================================================================")
    typewriter("\nGOODLUCK!")
    score = 0
    answer = input("\n1. What is the output?\nx = 10\nif x > 5:\n    print('Yes')\nelse:\n    print('No')\nA. Yes\nB. No\nC. Error\nD. Nothing\nAnswer: ")
    if answer.lower() == "a":
        typewriter("GREAT!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is A. Yes")
    answer = input("\n2. What is the output?\nfor i in range(1, 4):\n    print(i)\nA. 1 2 3\nB. 0 1 2\nC. 1 2 3 4\nD. Error\nAnswer: ")
    if answer.lower() == "a":
        typewriter("NICE!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is A. 1 2 3")
    answer = input("\n3. Which function returns a value?\nA. print()\nB. input()\nC. return\nD. def\nAnswer: ")
    if answer.lower() == "c":
        typewriter("GOOD JOB!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is C. return")
    answer = input("\n4. What does len() do?\nA. Adds numbers\nB. Counts items\nC. Converts data\nD. Loops data\nAnswer: ")
    if answer.lower() == "b":
        typewriter("VERY GOOD!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is B. Counts items")
    answer = input("\n5. What will this code print?\nname = 'Mark'\nprint(f'Hello {name}')\nA. Hello\nB. Hello name\nC. Hello Mark\nD. Error\nAnswer: ")
    if answer.lower() == "c":
        typewriter("AWESOME!")
        score += 1
    else:
        typewriter("WRONG!, The correct answer is C. Hello Mark")
    time.sleep(.5)
    print(f"\nYour final score is {score} / 5")
    time.sleep(.5)
    print("Quiz completed!")
    input("\npress enter to continue: ")
    os.system('cls')
