import os
import time

def one():
    os.system('cls')
    print("Python is a high-level, versatile programming language created by Dutch software engineer Guido van")
    time.sleep(.1)
    print("Rossum, who began its development in the late 1980s and released the first public version in 1991. Designed")
    time.sleep(.1)
    print("with an emphasis on readability and simplicity, Python uses clean, English-like syntax that makes it easier for")
    time.sleep(.1)
    print("beginners to learn while still offering powerful capabilities for experts. Van Rossum, often referred to as")
    time.sleep(.1)
    print("Python\'s \"Benevolent Dictator for Life\" (BDFL) until he stepped down from that role in 2018, drew inspiration")
    time.sleep(.1)
    print("from languages like ABC and aimed to create a language that encouraged clear, logical code. Over the years,")
    time.sleep(.1)
    print("Python has grown into one of the world\'s most popular languages, used across web development, data")
    time.sleep(.1)
    print("science, automation, artificial intelligence, and scientific computing, supported by a massive global")
    time.sleep(.1)
    print("community and an extensive ecosystem of libraries.")
    time.sleep(.1)
    print("=================================================================================================================\n")
    input("press enter to continue: ")
one()

def two():
    os.system('cls')
    print("Python is good for beginners because it is easy to read and understand. Its code looks simple, almost like")
    time.sleep(.1)
    print("normal English, so new learners don\'t get confused. It also has fewer rules and symbols, making it easier to")
    time.sleep(.1)
    print("write and fix mistakes. Python has a big community, which means there are many tutorials and examples")
    time.sleep(.1)
    print("available online for students. It can also be used for many things like making websites, automating tasks, or")
    time.sleep(.1)
    print("working with data, so beginners can explore different projects without changing languages. Overall, Python")
    time.sleep(.1)
    print("is simple, flexible, and beginner-friendly, which makes it a great first programming language.")
    time.sleep(.1)
    print("=================================================================================================================\n")
    time.sleep(.1)
